Live Belarus
unschooler97/java-helloworld pull request #5
Opened 2020-11-03 08:39 UTC by pavelgera

Done

2020-11-03 08:44 UTC, madhead commented
Отличное название и оформление!

Сейчас этот PR не может быть принят, потому что кто-то другой (#3) успел "отдать" свои изменения в ветку `main` (в ту же, в которую пытаешься отдать изменения и ты) вперёд тебя. Нужно обновить этот PR чтобы он мог быть принят. Предлагаю это сделать через [`rebase`](https://habr.com/ru/post/161009), а заодно и обьединить оба твоих коммита в один.

2020-11-03 19:48 UTC, madhead requested changes
Объедини все коммиты в один и обнови PR с учётом последних изменений в репозитории от других коллег.

2020-11-03 21:10 UTC, pavelgera commented
> Объедини все коммиты в один и обнови PR с учётом последних изменений в репозитории от других коллег.

in progress

2020-11-05 16:46 UTC, madhead requested changes

2020-11-05 16:46 UTC, madhead commented on Hello world
> +
Удали этот файл.

2020-11-05 17:02 UTC, madhead commented
@pavelgera, будешь коммиты обьединять?

2020-11-05 17:27 UTC, pavelgera commented
> @pavelgera, будешь коммиты обьединять?

я их удалил(

2020-11-05 18:44 UTC, madhead commented
@pavelgera, да, действительно. Поправишь?

2020-11-06 10:09 UTC, merged